In [7]:
import numpy as np 
#np.random.seed(0)

def sigmoid (x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

#Input datasets
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[0],[1],[1],[0]])

epochs = 10000
lr = 0.1
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1

#Random weights and bias initialization
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size=(1,outputLayerNeurons))
print(hidden_weights)
print(hidden_bias)
print(output_weights)
print(output_bias)
print("Initial hidden weights: ",end='')
print(*hidden_weights)
print("Initial hidden biases: ",end='')
print(*hidden_bias)
print("Initial output weights: ",end='')
print(*output_weights)
print("Initial output biases: ",end='')
print(*output_bias)


#Training algorithm
for _ in range(epochs):
	#Forward Propagation
	hidden_layer_activation = np.dot(inputs,hidden_weights)
	hidden_layer_activation += hidden_bias
	hidden_layer_output = sigmoid(hidden_layer_activation)

	output_layer_activation = np.dot(hidden_layer_output,output_weights)
	output_layer_activation += output_bias
	predicted_output = sigmoid(output_layer_activation)
	print(output_layer_activation)
	#Backpropagation
	error = expected_output - predicted_output
	d_predicted_output = error * sigmoid_derivative(predicted_output)
	
	error_hidden_layer = d_predicted_output.dot(output_weights.T)
	d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

	#Updating Weights and Biases
	output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
	output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
	hidden_weights += inputs.T.dot(d_hidden_layer) * lr
	hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr

print("Final hidden weights: ",end='')
print(*hidden_weights)
print("Final hidden bias: ",end='')
print(*hidden_bias)
print("Final output weights: ",end='')
print(*output_weights)
print("Final output bias: ",end='')
print(*output_bias)

print("\nOutput from neural network after 10,000 epochs: ",end='')
print(*predicted_output)

Streaming output truncated to the last 5000 lines.
 [-1.23993289]]
[[-2.06058526]
 [ 1.55991423]
 [ 1.56081086]
 [-1.24092942]]
[[-2.06086374]
 [ 1.56071817]
 [ 1.56160915]
 [-1.241925  ]]
[[-2.06114237]
 [ 1.56152148]
 [ 1.56240682]
 [-1.24291962]]
[[-2.06142116]
 [ 1.56232414]
 [ 1.56320389]
 [-1.2439133 ]]
[[-2.06170011]
 [ 1.56312618]
 [ 1.56400035]
 [-1.24490603]]
[[-2.06197921]
 [ 1.56392757]
 [ 1.56479621]
 [-1.24589782]]
[[-2.06225846]
 [ 1.56472834]
 [ 1.56559146]
 [-1.24688866]]
[[-2.06253787]
 [ 1.56552846]
 [ 1.5663861 ]
 [-1.24787855]]
[[-2.06281743]
 [ 1.56632796]
 [ 1.56718014]
 [-1.24886751]]
[[-2.06309713]
 [ 1.56712681]
 [ 1.56797356]
 [-1.24985551]]
[[-2.06337699]
 [ 1.56792504]
 [ 1.56876639]
 [-1.25084258]]
[[-2.06365699]
 [ 1.56872263]
 [ 1.5695586 ]
 [-1.25182871]]
[[-2.06393714]
 [ 1.56951959]
 [ 1.57035021]
 [-1.2528139 ]]
[[-2.06421744]
 [ 1.57031591]
 [ 1.57114122]
 [-1.25379815]]
[[-2.06449788]
 [ 1.5711116 ]
 [ 1.57193162]
 [-1.25478146]]
[[-2.06477846]
 [ 